// Mocks generated by Mockito 5.4.4 from annotations
// in junno_app/test/data/services/local/product/record_to_product_mapper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:junno_app/src/data/datasources/datasource_provider.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sembast/src/api/v2/database.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatasourceProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatasourceProvider extends _i1.Mock
    implements _i3.DatasourceProvider<_i2.Database> {
  @override
  _i4.Future<_i2.Database> get instance => (super.noSuchMethod(
        Invocation.getter(#instance),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#instance),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#instance),
        )),
      ) as _i4.Future<_i2.Database>);
}
